/**
 * Shared look-and-feel for data pages (grid view, ticket view, forms).
 * Pass current theme from useTheme().theme so colors follow light/dark mode.
 */
export function getDataPageStyles(t) {
  return {
    page: { fontFamily: t.fontFamily.sans },
    header: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      flexWrap: 'wrap',
      gap: 16,
      marginBottom: 24,
    },
    title: { margin: 0, fontSize: t.fontSize['2xl'], fontWeight: 600, color: t.color.text },
    toolbar: { display: 'flex', alignItems: 'center', gap: 12, flexWrap: 'wrap' },
    btn: {
      padding: `${t.button.paddingVertical} ${t.button.paddingHorizontal}`,
      fontSize: t.button.fontSize,
      fontWeight: t.button.fontWeight,
      fontFamily: t.fontFamily.sans,
      borderRadius: t.button.borderRadius,
      border: 'none',
      cursor: 'pointer',
    },
    btnPrimary: {
      background: t.button.primaryBg,
      color: t.button.primaryColor,
    },
    btnSecondary: {
      background: t.button.secondaryBg,
      color: t.button.secondaryColor,
      border: `1px solid ${t.button.secondaryBorder}`,
    },
    btnDanger: {
      background: 'transparent',
      color: t.color.error,
      border: `1px solid ${t.color.error}`,
    },
    formCard: {
      background: t.color.surface,
      borderRadius: 8,
      boxShadow: '0 2px 8px rgba(0,0,0,0.06)',
      padding: 20,
      marginBottom: 24,
    },
    formRow: { marginBottom: 16 },
    label: { display: 'block', marginBottom: 6, fontSize: t.fontSize.sm, fontWeight: 500, color: t.color.text },
    input: {
      width: '100%',
      maxWidth: 400,
      padding: '8px 12px',
      fontSize: t.fontSize.base,
      border: `1px solid ${t.color.border}`,
      borderRadius: t.button.borderRadius,
      fontFamily: t.fontFamily.sans,
      background: t.color.surface,
      color: t.color.text,
    },
    select: {
      width: '100%',
      maxWidth: 400,
      padding: '8px 12px',
      fontSize: t.fontSize.base,
      border: `1px solid ${t.color.border}`,
      borderRadius: t.button.borderRadius,
      fontFamily: t.fontFamily.sans,
      background: t.color.surface,
      color: t.color.text,
    },
    checkbox: { marginRight: 8, accentColor: t.iconColor },
    grid: (gridTemplateColumns) => ({
      display: 'grid',
      gridTemplateColumns,
      gap: 12,
      alignItems: 'center',
      background: t.color.surface,
      padding: '12px 16px',
      borderRadius: 8,
      boxShadow: '0 2px 8px rgba(0,0,0,0.06)',
      marginBottom: 8,
      fontFamily: t.fontFamily.sans,
      color: t.color.text,
    }),
    gridHeader: {
      fontWeight: 600,
      color: t.color.textMuted,
      fontSize: t.fontSize.sm,
    },
    ticketList: { display: 'flex', flexDirection: 'column', gap: 12 },
    ticketCard: {
      background: t.color.surface,
      borderRadius: 8,
      boxShadow: '0 2px 8px rgba(0,0,0,0.06)',
      padding: 16,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      flexWrap: 'wrap',
      gap: 12,
      color: t.color.text,
    },
    ticketMain: { display: 'flex', alignItems: 'center', gap: 12, flexWrap: 'wrap' },
    empty: { color: t.color.textMuted, padding: 24, textAlign: 'center' },
    actions: { display: 'flex', gap: 8 },
  };
}
